# Docker Compose configuration for production environment
# Use this file with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up


services:
  # Server Production Configuration
  server:
    build:
      target: production
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    # No volume mounts for production - use built image
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Web Production Configuration
  web:
    build:
      target: production
    environment:
      NODE_ENV: production
    # No volume mounts for production - use built image
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # PostgreSQL Production Configuration
  postgres:
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    # Consider using external managed database in real production

  # pgAdmin Production Configuration
  pgadmin:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M