version: '3.8'

services:
  # PostgreSQL with pgvector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: noteum-postgres
    environment:
      POSTGRES_DB: noteum
      POSTGRES_USER: noteum
      POSTGRES_PASSWORD: noteum123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noteum -d noteum"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - noteum-network

  # pgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: noteum-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@noteum.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - noteum-network
    profiles:
      - tools # 可选服务，使用 docker-compose --profile tools up 启动

volumes:
  postgres_data:
  pgadmin_data:

networks:
  noteum-network:
    driver: bridge