name: noteum-dev
x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - .:/app
  working_dir: /app
  env_file:
    - .env.development

services:
  server:
    <<: *common-config
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SUB_PKG: server
    ports:
      - "${SERVER_PORT:-9157}:${SERVER_PORT:-9157}" # API 服务
    environment:
      - ENV=development
      - SERVICE=${SERVER_PORT:-9157}
      - PORT=${SERVER_PORT:-9157}
      - APP_PORT=${SERVER_PORT:-9157}
    working_dir: /app/packages/server
    command: [ "bun", "run", "dev" ]
    depends_on:
      - postgres
  web:
    <<: *common-config
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SUB_PKG: web
    ports:
      - "${WEB_PORT:-9527}:${WEB_PORT:-9527}"
    environment:
      - NODE_ENV=development
      - SERVICE=${WEB_PORT:-9527}
      - PORT=${WEB_PORT:-9527}
      - APP_PORT=${WEB_PORT:-9527}
    working_dir: /app/packages/web
    command: [ "bun", "run", "dev" ]
    depends_on:
      - server
  postgres:
    image: pgvector/pgvector:0.8.0-pg16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    env_file:
      - .env.development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
