version: '3.8'

services:
  # PostgreSQL 数据库 with pgvector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: noteum-postgres-dev
    environment:
      POSTGRES_DB: noteum_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "9198:5432" # 使用标准化端口 9198
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - noteum-dev
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d noteum_dev" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: noteum-redis-dev
    ports:
      - "9178:6379" # 使用标准化端口 9178
    volumes:
      - redis_data_dev:/data
    networks:
      - noteum-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  # PgAdmin (数据库管理界面)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: noteum-pgadmin-dev
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_DEFAULT_EMAIL: admin@noteum.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9188:80" # 使用标准化端口 9188
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    networks:
      - noteum-dev
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis 管理界面
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: noteum-redis-commander-dev
    ports:
      - "9189:8081" # 使用端口 9189 避免冲突
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
    networks:
      - noteum-dev
    restart: unless-stopped

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  nestjs_logs_dev:
    driver: local
  pgadmin_data_dev:
    driver: local
  nestjs_node_modules:
    driver: local
  client_node_modules:
    driver: local
  packages_node_modules:
    driver: local

networks:
  noteum-dev:
    driver: bridge
