/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PingImport } from './routes/ping'
import { Route as FlowImport } from './routes/flow'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PingRoute = PingImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRoute,
} as any)

const FlowRoute = FlowImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowImport
      parentRoute: typeof rootRoute
    }
    '/ping': {
      id: '/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flow': typeof FlowRoute
  '/ping': typeof PingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flow': typeof FlowRoute
  '/ping': typeof PingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/flow': typeof FlowRoute
  '/ping': typeof PingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flow' | '/ping'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flow' | '/ping'
  id: '__root__' | '/' | '/flow' | '/ping'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowRoute: typeof FlowRoute
  PingRoute: typeof PingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowRoute: FlowRoute,
  PingRoute: PingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flow",
        "/ping"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/flow": {
      "filePath": "flow.tsx"
    },
    "/ping": {
      "filePath": "ping.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
