# Tauri 测试配置
[build]
# 启用并行构建
jobs = 4

# 测试配置
[target.'cfg(test)']
# 启用测试优化
opt-level = 1
# 启用调试信息
debug = true

# 开发配置
[profile.dev]
# 优化开发构建
opt-level = 1
# 启用调试信息
debug = true
# 快速重新编译
incremental = true
# 代码生成单元
codegen-units = 256

# 测试配置
[profile.test]
# 测试优化级别
opt-level = 1
# 启用调试信息
debug = true
# 启用溢出检查
overflow-checks = true
# 启用调试断言
debug-assertions = true

# 性能测试配置
[profile.bench]
# 基准测试优化
opt-level = 3
# 禁用调试信息
debug = false
# 启用 LTO 优化
lto = true
# 单个代码生成单元
codegen-units = 1