name: Version and Changelog

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          lfs: true
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Setup Bun cache
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen

      - name: Git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Build packages
        run: |
          # 创建每个包的构建目录
          mkdir -p packages/utils/dist
          mkdir -p packages/core/dist
          mkdir -p packages/ui/dist
          mkdir -p packages/server/dist
          mkdir -p packages/web/dist
          
          # 运行构建脚本
          bun run build

      - name: Clean build artifacts
        run: |
          find . -name "*.tsbuildinfo" -delete
          git checkout -- "*.tsbuildinfo" || true

      - name: Version and publish
        run: |
          bun run version --yes
          git push --follow-tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
